repos:

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        stages: [ commit ]

 

      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        stages: [ commit ]

 

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [ python ]
        stages: [commit]

 

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        require_serial: true
        stages: [commit]

 

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]
        require_serial: true
        verbose: true
        stages: [commit]

 

      - id: tests
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        stages: [commit]