version:  "3.9"

services:
  logal:
    container_name: log_analyser
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./app_logs:/app/app_logs